### ISSUE TITLE
Upgrade to Heroicons v2

### ISSUE THREAD

**Issue by davidruvolo51** [davidruvolo51/rheroicons#30]
[Heroicons v2](https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0) is now available. This will be a larger release as the structure of the release has changed, more icons were added, and a new mini style was introduced. This will also be a breaking change as many icons were renamed or removed.

## Tasks

- [x] Check directory structure and update convert script accordingly
- [x] Rewrite convert script to python
- [x] Convert Heroicons v2 library
- [x] Fix unit tests (make sure all tests are updates to v2)
- [x] Update icon gallery
- [x] Update documentation
- [x] Improve examples
- [x] Run checks and fix any issues
- [x] Submit to cran

**Comment by davidruvolo51** [comment]
Make sure the documentation is updated. It is important to highlight the major changes (new icons, styles, and sizes). Update the examples.

**Comment by davidruvolo51** [comment]
Integrate #31 into version 1.0
